flash_tolerance: 0.01
binning_decimals: 2
B: 100
k: 5
seed: 42

similarity_threshold: 0.7

support_threshold: 0.5
max_component_size: 20

rescue_similarity_threshold: 0.3
use_average_similarity: false
cache_similarity: true

folder: "."
cache_folder: "../cache"
similarity_type: "cos"

base_graph_path: ../results/base.cx
threshold_graph_path: ../results/threshold.cx
rescued_graph_path: ../results/rescued.cx
