# Execution & Pipeline Settings
environment:
  python_bin: ".venv/Scripts/python.exe"   # Windows

# Paths to Input Files & Models
inputs:
  # name of the test_file mgf (pre-cleaning)
  raw_mgf:      "data/test_file.mgf"
      
models:z
  # the below files are required and can be downloaded by running setup.py
  ms2deepscore: "data/ms2deepscore_model.pt"
  spec2vec:     "data/Spec2VecModel.model"
  structure_db: "data/coconut_db.jsonl"

paths:
  result_dir: "results"

# Pipeline Wildcards & Parameters

# these parameters allow for running of multiple variations by adding the the lists below
# note that computational time will grow significantly with more possible variations

parameters:
  max_component_sizes:
    - 100         # other options: any positive integer
  similarity_types:
    - "modcos"    # other options: "modcos", "spec2vec", "ms2deepscore"
  matrix_types:
    - "normal"    # other options: "normal", "average"
  graph_types:
    - "threshold" # other options: "base", "threshold", "rescued"
  nr_of_motifs:
    - 300         # other options: any positive integer

# Module Specific Parameters
params_files:
  mn:     "snakemake/params/mn.yaml"
  snapms: "snakemake/params/snapms.yaml"
  ms2lda: "snakemake/params/ms2lda.yaml"
