from pathlib import Path
import os

# --- MS2LDa stuff ---
LDA_MODEL       = "/lustre/BIF/nobackup/ijcke001/exp/media_screening_motifs/600_model.model"
MOTIFS          = "/lustre/BIF/nobackup/ijcke001/exp/media_screening_motifs/600_motifs.mgf"
LIBRARY         = "/lustre/BIF/nobackup/ijcke001/supporting_files/msnlib_db_positive_mode.mgf"
INTERSECTION    = "/lustre/BIF/nobackup/ijcke001/supporting_files/coconut_msnlib_intersection.mgf"

# --- Experiment Files ---
RESULT_FOLDER   = "/lustre/BIF/nobackup/ijcke001/media_screening055"
INPUT_MGF       = "/lustre/BIF/nobackup/ijcke001/experimental_data/media_screening.mgf"

# --- Environment ---
PYTHON  = "/lustre/BIF/nobackup/ijcke001/miniforge3/envs/mn310/bin/python"
REPO    = "/home/ijcke001/CMNA"

# --- Models and Databases ---
MS2DEEPSCORE_MODEL_PATH     = "/lustre/BIF/nobackup/ijcke001/supporting_files/ms2deepscore_model.pt"
SPEC2VEC_MODEL_PATH         = "/lustre/BIF/nobackup/ijcke001/supporting_files/Spec2VecModel.model"
STRUCTURE_DB                = "/lustre/BIF/nobackup/ijcke001/supporting_files/coconut_db.jsonl"

# --- Dynamically created paths and variables ---

# files in parent folder
SNAKEFILE_DIR = Path(workflow.basedir)
MN_PARAMS     = str(SNAKEFILE_DIR / "params_mn.yaml")
SNAPMS_PARAMS = str(SNAKEFILE_DIR / "params_snapms.yaml")
MS2LDA_PARAMS = str(SNAKEFILE_DIR / "params_ms2lda.yaml")

# naming based on input mgf
STEM = Path(INPUT_MGF).stem
CLEANED_MGF = f"{RESULT_FOLDER}/{STEM}_cleaned.mgf"

# --- Wildcards ---

# variations
MAX_COMPONENT_SIZES = [
    20,
    50,
    100
]
SIMILARITY_TYPES = [
    "ms2deepscore",
    "spec2vec",
    "modcos"
]
MATRIX_TYPES = [
    "normal",
    "average"
]
GRAPH_TYPES = [
    "threshold",
    "base",
    "rescued"
]

wildcard_constraints:
    similarity_type    = "|".join(SIMILARITY_TYPES),
    max_component_size = "|".join([str(x) for x in MAX_COMPONENT_SIZES]),
    matrix_type        = "|".join(MATRIX_TYPES),
    graph_type         = "|".join(GRAPH_TYPES),

# --- functions ---

def get_dynamic_threshold(wildcards): # ms2deepscore requires threshold of 0.8, others require 0.7
    if wildcards.similarity_type == "ms2deepscore":
        return "--similarity-threshold 0.85"
    else:
        return "--similarity-threshold 0.7"


def get_dynamic_matrix(wildcards): # converts a wildcard into a boolean flag for the CLI
    if wildcards.matrix_type == "average":
        return "--use-average-similarity"
    else:
        return ""

# --- rules ---

rule all:
    input:
        expand(
            f"{RESULT_FOLDER}/{{similarity_type}}_{{max_component_size}}_{{matrix_type}}_{STEM}_{{graph_type}}.cx",
            similarity_type=SIMILARITY_TYPES, matrix_type=MATRIX_TYPES, graph_type=GRAPH_TYPES, max_component_size=MAX_COMPONENT_SIZES
        ),
        expand(
            f"{RESULT_FOLDER}/snapms_{{similarity_type}}_{{max_component_size}}_{{matrix_type}}_{STEM}_{{graph_type}}",
            similarity_type=SIMILARITY_TYPES, matrix_type=MATRIX_TYPES, graph_type=GRAPH_TYPES, max_component_size=MAX_COMPONENT_SIZES

        ),
        #directory(f"{RESULT_FOLDER}/media_screening_motif_plots")
        #plots       = f"{RESULT_FOLDER}/media_screening_motif_plots",
        #mgf_matches = f"{RESULT_FOLDER}/motif_library_matches"


rule clean_mgf:
    input:
        mgf = INPUT_MGF
    output:
        mgf = CLEANED_MGF
    shell:
        """
        {PYTHON} {REPO}/src/cleaning/mn_cleaning.py \
            --raw-mgf {input.mgf} \
            --cleaned-mgf {output.mgf}
        """


# builds a mn based on the mgf in the batch folder
rule mn:
    input:
        mgf                 = CLEANED_MGF,
        params              = MN_PARAMS,
        ms2deepscore_model  = MS2DEEPSCORE_MODEL_PATH,
        spec2vec_model      = SPEC2VEC_MODEL_PATH
    output:
        base      = f"{RESULT_FOLDER}/{{similarity_type}}_{{max_component_size}}_{{matrix_type}}_{STEM}_base.cx",
        threshold = f"{RESULT_FOLDER}/{{similarity_type}}_{{max_component_size}}_{{matrix_type}}_{STEM}_threshold.cx",
        rescued   = f"{RESULT_FOLDER}/{{similarity_type}}_{{max_component_size}}_{{matrix_type}}_{STEM}_rescued.cx"
    params:
        threshold   = get_dynamic_threshold,
        matrix      = get_dynamic_matrix
    shell:
        """
        {PYTHON} {REPO}/src/mn \
            --folder {RESULT_FOLDER} \
            --defaults {input.params} \
            --mgf-cleaned {input.mgf} \
            --ms2deepscore-model-path {input.ms2deepscore_model} \
            --spec2vec-model-path {input.spec2vec_model} \
            --similarity-type {wildcards.similarity_type} \
            --max-component-size {wildcards.max_component_size} \
            --base-graph-path {output.base} \
            --threshold-graph-path {output.threshold} \
            --rescued-graph-path {output.rescued} \
            --average-similarity-file {RESULT_FOLDER}/{wildcards.similarity_type}_average_similarity.npz \
            --similarity-file {RESULT_FOLDER}/{wildcards.similarity_type}_similarity.npz \
            --support-file {RESULT_FOLDER}/{wildcards.similarity_type}_support.npz \
            {params.threshold} \
            {params.matrix}
        """


rule motif_overlap:
    input:
        lda_model = LDA_MODEL,
        mgf = CLEANED_MGF
    output:
        overlaps = f"{RESULT_FOLDER}/motif_overlaps.csv"
    shell:
        """
        {PYTHON} {REPO}/src/motif_metadata/motif_detection.py \
            --folder {RESULT_FOLDER} \
            --mgf {input.mgf} \
            --model {input.lda_model} \
            --result {output.overlaps} \
            --dataset-acquisition-type DDA \
            --dataset-significant-digits 2
        """


rule snapms:
    input:
        params      = SNAPMS_PARAMS,
        mn          = f"{RESULT_FOLDER}/{{similarity_type}}_{{max_component_size}}_{{matrix_type}}_{STEM}_{{graph_type}}.cx",
        overlaps    = f"{RESULT_FOLDER}/motif_overlaps.csv",
        model       = MS2DEEPSCORE_MODEL_PATH,
        mgf         = CLEANED_MGF
    output:
        result_folder = directory(f"{RESULT_FOLDER}/snapms_{{similarity_type}}_{{max_component_size}}_{{matrix_type}}_{STEM}_{{graph_type}}"),
    shell:
        """
        {PYTHON} {REPO}/src/motif_metadata/mn_motif_metadata.py \
            --mn-file {input.mn} \
            --overlaps {input.overlaps} \
            --threshold 0.01
        {PYTHON} {REPO}/src/snapms \
            --graph {input.mn} \
            --defaults {input.params} \
            --result-folder {output.result_folder} \
            --reference-db {STRUCTURE_DB}
        {PYTHON} {REPO}/src/annotation_metadata/relay_annotation_info.py \
            --mn-file {input.mn} \
            --annotation-folder {output.result_folder}
        {PYTHON} {REPO}/src/annotation_metadata/smiles_flag.py \
            --mn-file {input.mn} \
            --annotation-folder {output.result_folder}
        """


rule plot_motifs:
    input:
        motifs  = MOTIFS,
        model   = LDA_MODEL,
        params  = MS2LDA_PARAMS,
        mgf     = CLEANED_MGF
    output:
        result_folder = directory(f"{RESULT_FOLDER}/media_screening_motif_plots")
    shell:
        """
        {PYTHON} {REPO}/src/motif_metadata/spectral_plots.py \
            --folder {RESULT_FOLDER} \
            --defaults {input.params} \
            --library {input.mgf} \
            --query {input.motifs} \
            --similarity-type overlap \
            --flash-tolerance 0.01 \
            --lda-model-path {input.model} \
            --max-batch-size 200 \
            --similarity-threshold 0.01 \
            --top-n 100 \
            --result-folder {output.result_folder}
        """


rule spectra_library_search:
    input:
        library         = LIBRARY,
        spec2vec_model  = SPEC2VEC_MODEL_PATH,
        query           = MOTIFS
    output:
        result_folder   = directory(f"{RESULT_FOLDER}/motif_library_matches")
    shell:
        """
        {PYTHON} {REPO}/src/motif_metadata/spectral_plots.py \
            --folder {RESULT_FOLDER} \
            --library {input.library} \
            --query {input.query} \
            --spec2vec-model-path {input.spec2vec_model} \
            --similarity-type spec2vec \
            --max-batch-size 200 \
            --top-n 40 \
            --similarity-threshold 0.7 \
            --result-folder {output.result_folder}
        """
